// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ViunaGuard.Data;

#nullable disable

namespace ViunaGuard.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20230904070225_AuthoritiesRemoved")]
    partial class AuthoritiesRemoved
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CarPerson", b =>
                {
                    b.Property<int>("CarsId")
                        .HasColumnType("int");

                    b.Property<int>("PeopleId")
                        .HasColumnType("int");

                    b.HasKey("CarsId", "PeopleId");

                    b.HasIndex("PeopleId");

                    b.ToTable("CarPerson");
                });

            modelBuilder.Entity("OrganizationPerson", b =>
                {
                    b.Property<int>("AreBannedId")
                        .HasColumnType("int");

                    b.Property<int>("BannedFromId")
                        .HasColumnType("int");

                    b.HasKey("AreBannedId", "BannedFromId");

                    b.HasIndex("BannedFromId");

                    b.ToTable("BlackList", (string)null);
                });

            modelBuilder.Entity("ViunaGuard.Models.AuthIdToViunaId", b =>
                {
                    b.Property<Guid>("AuthId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ViunaUserId")
                        .HasColumnType("int");

                    b.HasKey("AuthId");

                    b.ToTable("AuthIds");
                });

            modelBuilder.Entity("ViunaGuard.Models.Car", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("BrandId")
                        .HasColumnType("int");

                    b.Property<int?>("ColorId")
                        .HasColumnType("int");

                    b.Property<string>("LicenseNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("ModelId")
                        .HasColumnType("int");

                    b.Property<string>("VIN")
                        .HasMaxLength(17)
                        .HasColumnType("nvarchar(17)");

                    b.HasKey("Id");

                    b.HasIndex("BrandId");

                    b.HasIndex("ColorId");

                    b.HasIndex("LicenseNumber")
                        .IsUnique();

                    b.HasIndex("ModelId");

                    b.ToTable("Cars");
                });

            modelBuilder.Entity("ViunaGuard.Models.Door", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OrganizationId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId");

                    b.ToTable("Doors");
                });

            modelBuilder.Entity("ViunaGuard.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EmployeeTypeId")
                        .HasColumnType("int");

                    b.Property<int>("OrganizationId")
                        .HasColumnType("int");

                    b.Property<int>("PersonId")
                        .HasColumnType("int");

                    b.Property<string>("PersonnelId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserAccessRoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeTypeId");

                    b.HasIndex("OrganizationId");

                    b.HasIndex("PersonId");

                    b.HasIndex("UserAccessRoleId");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("ViunaGuard.Models.EmployeePeriodicShift", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FinishTime")
                        .HasColumnType("datetime2");

                    b.Property<int?>("GuardDoorId")
                        .HasColumnType("int");

                    b.Property<int>("OrganizationId")
                        .HasColumnType("int");

                    b.Property<int>("PeriodDayRange")
                        .HasColumnType("int");

                    b.Property<int?>("ShiftMakerEmployeeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("GuardDoorId");

                    b.HasIndex("OrganizationId");

                    b.HasIndex("ShiftMakerEmployeeId");

                    b.ToTable("EmployeePeriodicShifts");
                });

            modelBuilder.Entity("ViunaGuard.Models.EmployeeShift", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FinishTime")
                        .HasColumnType("datetime2");

                    b.Property<int?>("GuardDoorId")
                        .HasColumnType("int");

                    b.Property<int>("OrganizationId")
                        .HasColumnType("int");

                    b.Property<int?>("ShiftMakerEmployeeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("GuardDoorId");

                    b.HasIndex("OrganizationId");

                    b.HasIndex("ShiftMakerEmployeeId");

                    b.ToTable("EmployeeShifts");
                });

            modelBuilder.Entity("ViunaGuard.Models.EmployeeShiftPeriodicMonthly", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DayOfMonth")
                        .HasColumnType("int");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FinishTime")
                        .HasColumnType("datetime2");

                    b.Property<int?>("GuardDoorId")
                        .HasColumnType("int");

                    b.Property<int>("OrganizationId")
                        .HasColumnType("int");

                    b.Property<int?>("ShiftMakerEmployeeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("GuardDoorId");

                    b.HasIndex("OrganizationId");

                    b.HasIndex("ShiftMakerEmployeeId");

                    b.ToTable("EmployeeShiftsPeriodicMonthly");
                });

            modelBuilder.Entity("ViunaGuard.Models.Entrance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CarId")
                        .HasColumnType("int");

                    b.Property<int>("EntranceGroupId")
                        .HasColumnType("int");

                    b.Property<int?>("GuestCount")
                        .HasColumnType("int");

                    b.Property<bool>("IsDriver")
                        .HasColumnType("bit");

                    b.Property<int?>("OrganizationId")
                        .HasColumnType("int");

                    b.Property<int>("PersonId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CarId");

                    b.HasIndex("EntranceGroupId");

                    b.HasIndex("OrganizationId");

                    b.HasIndex("PersonId");

                    b.ToTable("Entrances");
                });

            modelBuilder.Entity("ViunaGuard.Models.EntranceGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DoorId")
                        .HasColumnType("int");

                    b.Property<int>("EnterOrExitId")
                        .HasColumnType("int");

                    b.Property<int>("GuardId")
                        .HasColumnType("int");

                    b.Property<int>("OrganizationId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Time")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("DoorId");

                    b.HasIndex("EnterOrExitId");

                    b.HasIndex("GuardId");

                    b.HasIndex("OrganizationId");

                    b.ToTable("EntranceGroups");
                });

            modelBuilder.Entity("ViunaGuard.Models.EntrancePermission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CarId")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndValidityTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("OrganizationId")
                        .HasColumnType("int");

                    b.Property<bool>("PermissionGranted")
                        .HasColumnType("bit");

                    b.Property<int>("PersonId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartValidityTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CarId");

                    b.HasIndex("OrganizationId");

                    b.HasIndex("PersonId");

                    b.ToTable("EntrancePermissions");
                });

            modelBuilder.Entity("ViunaGuard.Models.EntrancePolicie", b =>
                {
                    b.Property<int>("DoorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DoorId"));

                    b.Property<bool>("CheckCars")
                        .HasColumnType("bit");

                    b.Property<bool>("CheckPoeple")
                        .HasColumnType("bit");

                    b.HasKey("DoorId");

                    b.ToTable("EntrancePolicies");
                });

            modelBuilder.Entity("ViunaGuard.Models.Enums.CarBrand", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CarBrands");
                });

            modelBuilder.Entity("ViunaGuard.Models.Enums.CarModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CarModels");
                });

            modelBuilder.Entity("ViunaGuard.Models.Enums.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Cities");
                });

            modelBuilder.Entity("ViunaGuard.Models.Enums.Color", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Colors");
                });

            modelBuilder.Entity("ViunaGuard.Models.Enums.EducationalDegree", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Degree")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("EducationalDegrees");
                });

            modelBuilder.Entity("ViunaGuard.Models.Enums.EmployeeType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("EmployeeTypes");
                });

            modelBuilder.Entity("ViunaGuard.Models.Enums.EnterOrExit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("EnterOrExit");
                });

            modelBuilder.Entity("ViunaGuard.Models.Enums.Gender", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Genders");
                });

            modelBuilder.Entity("ViunaGuard.Models.Enums.MaritalStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Stat")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("MaritalStatuses");
                });

            modelBuilder.Entity("ViunaGuard.Models.Enums.MilitaryServiceStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Stat")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("MilitaryServiceStatuses");
                });

            modelBuilder.Entity("ViunaGuard.Models.Enums.Nationality", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Nationalities");
                });

            modelBuilder.Entity("ViunaGuard.Models.Enums.Religion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Religions");
                });

            modelBuilder.Entity("ViunaGuard.Models.Organization", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Organizations");
                });

            modelBuilder.Entity("ViunaGuard.Models.OrganizationPolicy", b =>
                {
                    b.Property<int>("OrganizationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrganizationId"));

                    b.Property<bool>("CheckCarsOnConferenceMode")
                        .HasColumnType("bit");

                    b.Property<bool>("CheckGuests")
                        .HasColumnType("bit");

                    b.Property<bool>("CheckUnregisteredGuests")
                        .HasColumnType("bit");

                    b.Property<bool>("CheckpeopleOnConferenceMode")
                        .HasColumnType("bit");

                    b.HasKey("OrganizationId");

                    b.ToTable("OrganizationPolicies");
                });

            modelBuilder.Entity("ViunaGuard.Models.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("BirthDay")
                        .HasColumnType("date");

                    b.Property<int?>("BirthPlaceCityId")
                        .HasColumnType("int");

                    b.Property<string>("CellPhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CityOfResidenceId")
                        .HasColumnType("int");

                    b.Property<int?>("EducationalDegreeId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FathersName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("GenderId")
                        .HasColumnType("int");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("MaritalStatusId")
                        .HasColumnType("int");

                    b.Property<int?>("MilitaryServiceStatusId")
                        .HasColumnType("int");

                    b.Property<string>("NationalId")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int?>("NationalityId")
                        .HasColumnType("int");

                    b.Property<int>("PersonAdditionalInfoId")
                        .HasColumnType("int");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ReligionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BirthPlaceCityId");

                    b.HasIndex("CityOfResidenceId");

                    b.HasIndex("EducationalDegreeId");

                    b.HasIndex("GenderId");

                    b.HasIndex("MaritalStatusId");

                    b.HasIndex("MilitaryServiceStatusId");

                    b.HasIndex("NationalId")
                        .IsUnique();

                    b.HasIndex("NationalityId");

                    b.HasIndex("PersonAdditionalInfoId");

                    b.HasIndex("ReligionId");

                    b.ToTable("People");
                });

            modelBuilder.Entity("ViunaGuard.Models.PersonAdditionalInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.HasKey("Id");

                    b.ToTable("PersonAdditionalInfos");
                });

            modelBuilder.Entity("ViunaGuard.Models.SignatureNeedForEntrancePermission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("MinAuthorityLevel")
                        .HasColumnType("int");

                    b.Property<int>("OrganizationId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId");

                    b.ToTable("SignatureNeedForEntrancePermissions");
                });

            modelBuilder.Entity("ViunaGuard.Models.SignedEntrancePermission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AuthorityLevel")
                        .HasColumnType("int");

                    b.Property<int>("EntrancePermissionId")
                        .HasColumnType("int");

                    b.Property<int>("OrganizationId")
                        .HasColumnType("int");

                    b.Property<int>("SignedByEmployeeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EntrancePermissionId");

                    b.HasIndex("OrganizationId");

                    b.HasIndex("SignedByEmployeeId");

                    b.ToTable("SignedEntrancePermissions");
                });

            modelBuilder.Entity("ViunaGuard.Models.UserAccess", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("AlwaysHaveEntrancePermission")
                        .HasColumnType("bit");

                    b.Property<bool>("CanBringGuests")
                        .HasColumnType("bit");

                    b.Property<bool>("CanChangeShifts")
                        .HasColumnType("bit");

                    b.Property<bool>("CanInviteGuests")
                        .HasColumnType("bit");

                    b.Property<bool>("CanSeeOtherDoorsEntrances")
                        .HasColumnType("bit");

                    b.Property<bool>("CanSeeOtherGuardsEntrances")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("UserAccesses");
                });

            modelBuilder.Entity("ViunaGuard.Models.UserAccessRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserAccessId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserAccessId");

                    b.ToTable("UserAccessRole");
                });

            modelBuilder.Entity("CarPerson", b =>
                {
                    b.HasOne("ViunaGuard.Models.Car", null)
                        .WithMany()
                        .HasForeignKey("CarsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ViunaGuard.Models.Person", null)
                        .WithMany()
                        .HasForeignKey("PeopleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("OrganizationPerson", b =>
                {
                    b.HasOne("ViunaGuard.Models.Person", null)
                        .WithMany()
                        .HasForeignKey("AreBannedId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ViunaGuard.Models.Organization", null)
                        .WithMany()
                        .HasForeignKey("BannedFromId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ViunaGuard.Models.Car", b =>
                {
                    b.HasOne("ViunaGuard.Models.Enums.CarBrand", "CarBrand")
                        .WithMany()
                        .HasForeignKey("BrandId");

                    b.HasOne("ViunaGuard.Models.Enums.Color", "Color")
                        .WithMany()
                        .HasForeignKey("ColorId");

                    b.HasOne("ViunaGuard.Models.Enums.CarModel", "CarModel")
                        .WithMany()
                        .HasForeignKey("ModelId");

                    b.Navigation("CarBrand");

                    b.Navigation("CarModel");

                    b.Navigation("Color");
                });

            modelBuilder.Entity("ViunaGuard.Models.Door", b =>
                {
                    b.HasOne("ViunaGuard.Models.Organization", "Organization")
                        .WithMany("Doors")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("ViunaGuard.Models.Employee", b =>
                {
                    b.HasOne("ViunaGuard.Models.Enums.EmployeeType", "EmployeeType")
                        .WithMany()
                        .HasForeignKey("EmployeeTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ViunaGuard.Models.Organization", "Organization")
                        .WithMany("Employees")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ViunaGuard.Models.Person", "Person")
                        .WithMany("Jobs")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ViunaGuard.Models.UserAccessRole", "UserAccessRole")
                        .WithMany()
                        .HasForeignKey("UserAccessRoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EmployeeType");

                    b.Navigation("Organization");

                    b.Navigation("Person");

                    b.Navigation("UserAccessRole");
                });

            modelBuilder.Entity("ViunaGuard.Models.EmployeePeriodicShift", b =>
                {
                    b.HasOne("ViunaGuard.Models.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ViunaGuard.Models.Door", "GuardDoor")
                        .WithMany()
                        .HasForeignKey("GuardDoorId");

                    b.HasOne("ViunaGuard.Models.Organization", "Organization")
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ViunaGuard.Models.Employee", "ShiftMakerEmployee")
                        .WithMany()
                        .HasForeignKey("ShiftMakerEmployeeId");

                    b.Navigation("Employee");

                    b.Navigation("GuardDoor");

                    b.Navigation("Organization");

                    b.Navigation("ShiftMakerEmployee");
                });

            modelBuilder.Entity("ViunaGuard.Models.EmployeeShift", b =>
                {
                    b.HasOne("ViunaGuard.Models.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ViunaGuard.Models.Door", "GuardDoor")
                        .WithMany("EmployeeShifts")
                        .HasForeignKey("GuardDoorId");

                    b.HasOne("ViunaGuard.Models.Organization", "Organization")
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ViunaGuard.Models.Employee", "ShiftMakerEmployee")
                        .WithMany()
                        .HasForeignKey("ShiftMakerEmployeeId");

                    b.Navigation("Employee");

                    b.Navigation("GuardDoor");

                    b.Navigation("Organization");

                    b.Navigation("ShiftMakerEmployee");
                });

            modelBuilder.Entity("ViunaGuard.Models.EmployeeShiftPeriodicMonthly", b =>
                {
                    b.HasOne("ViunaGuard.Models.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ViunaGuard.Models.Door", "GuardDoor")
                        .WithMany()
                        .HasForeignKey("GuardDoorId");

                    b.HasOne("ViunaGuard.Models.Organization", "Organization")
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ViunaGuard.Models.Employee", "ShiftMakerEmployee")
                        .WithMany()
                        .HasForeignKey("ShiftMakerEmployeeId");

                    b.Navigation("Employee");

                    b.Navigation("GuardDoor");

                    b.Navigation("Organization");

                    b.Navigation("ShiftMakerEmployee");
                });

            modelBuilder.Entity("ViunaGuard.Models.Entrance", b =>
                {
                    b.HasOne("ViunaGuard.Models.Car", "Car")
                        .WithMany()
                        .HasForeignKey("CarId");

                    b.HasOne("ViunaGuard.Models.EntranceGroup", "EntranceGroup")
                        .WithMany("Entrances")
                        .HasForeignKey("EntranceGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ViunaGuard.Models.Organization", null)
                        .WithMany("Entrances")
                        .HasForeignKey("OrganizationId");

                    b.HasOne("ViunaGuard.Models.Person", "Person")
                        .WithMany("Entrances")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Car");

                    b.Navigation("EntranceGroup");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("ViunaGuard.Models.EntranceGroup", b =>
                {
                    b.HasOne("ViunaGuard.Models.Door", "Door")
                        .WithMany()
                        .HasForeignKey("DoorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ViunaGuard.Models.Enums.EnterOrExit", "EnterOrExit")
                        .WithMany()
                        .HasForeignKey("EnterOrExitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ViunaGuard.Models.Employee", "Guard")
                        .WithMany()
                        .HasForeignKey("GuardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ViunaGuard.Models.Organization", "Organization")
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Door");

                    b.Navigation("EnterOrExit");

                    b.Navigation("Guard");

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("ViunaGuard.Models.EntrancePermission", b =>
                {
                    b.HasOne("ViunaGuard.Models.Car", "Car")
                        .WithMany()
                        .HasForeignKey("CarId");

                    b.HasOne("ViunaGuard.Models.Organization", "Organization")
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ViunaGuard.Models.Person", "Person")
                        .WithMany("EntrancePermissions")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Car");

                    b.Navigation("Organization");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("ViunaGuard.Models.Person", b =>
                {
                    b.HasOne("ViunaGuard.Models.Enums.City", "BirthPlaceCity")
                        .WithMany()
                        .HasForeignKey("BirthPlaceCityId");

                    b.HasOne("ViunaGuard.Models.Enums.City", "CityOfResidence")
                        .WithMany()
                        .HasForeignKey("CityOfResidenceId");

                    b.HasOne("ViunaGuard.Models.Enums.EducationalDegree", "EducationalDegree")
                        .WithMany()
                        .HasForeignKey("EducationalDegreeId");

                    b.HasOne("ViunaGuard.Models.Enums.Gender", "Gender")
                        .WithMany()
                        .HasForeignKey("GenderId");

                    b.HasOne("ViunaGuard.Models.Enums.MaritalStatus", "MaritalStatus")
                        .WithMany()
                        .HasForeignKey("MaritalStatusId");

                    b.HasOne("ViunaGuard.Models.Enums.MilitaryServiceStatus", "MilitaryServiceStatus")
                        .WithMany()
                        .HasForeignKey("MilitaryServiceStatusId");

                    b.HasOne("ViunaGuard.Models.Enums.Nationality", "Nationality")
                        .WithMany()
                        .HasForeignKey("NationalityId");

                    b.HasOne("ViunaGuard.Models.PersonAdditionalInfo", "PersonAdditionalInfo")
                        .WithMany()
                        .HasForeignKey("PersonAdditionalInfoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ViunaGuard.Models.Enums.Religion", "Religion")
                        .WithMany()
                        .HasForeignKey("ReligionId");

                    b.Navigation("BirthPlaceCity");

                    b.Navigation("CityOfResidence");

                    b.Navigation("EducationalDegree");

                    b.Navigation("Gender");

                    b.Navigation("MaritalStatus");

                    b.Navigation("MilitaryServiceStatus");

                    b.Navigation("Nationality");

                    b.Navigation("PersonAdditionalInfo");

                    b.Navigation("Religion");
                });

            modelBuilder.Entity("ViunaGuard.Models.SignatureNeedForEntrancePermission", b =>
                {
                    b.HasOne("ViunaGuard.Models.Organization", "Organization")
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("ViunaGuard.Models.SignedEntrancePermission", b =>
                {
                    b.HasOne("ViunaGuard.Models.EntrancePermission", "EntrancePermission")
                        .WithMany("Signatures")
                        .HasForeignKey("EntrancePermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ViunaGuard.Models.Organization", "Organization")
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ViunaGuard.Models.Employee", "SigningEmployee")
                        .WithMany()
                        .HasForeignKey("SignedByEmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EntrancePermission");

                    b.Navigation("Organization");

                    b.Navigation("SigningEmployee");
                });

            modelBuilder.Entity("ViunaGuard.Models.UserAccessRole", b =>
                {
                    b.HasOne("ViunaGuard.Models.UserAccess", "UserAccess")
                        .WithMany()
                        .HasForeignKey("UserAccessId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserAccess");
                });

            modelBuilder.Entity("ViunaGuard.Models.Door", b =>
                {
                    b.Navigation("EmployeeShifts");
                });

            modelBuilder.Entity("ViunaGuard.Models.EntranceGroup", b =>
                {
                    b.Navigation("Entrances");
                });

            modelBuilder.Entity("ViunaGuard.Models.EntrancePermission", b =>
                {
                    b.Navigation("Signatures");
                });

            modelBuilder.Entity("ViunaGuard.Models.Organization", b =>
                {
                    b.Navigation("Doors");

                    b.Navigation("Employees");

                    b.Navigation("Entrances");
                });

            modelBuilder.Entity("ViunaGuard.Models.Person", b =>
                {
                    b.Navigation("EntrancePermissions");

                    b.Navigation("Entrances");

                    b.Navigation("Jobs");
                });
#pragma warning restore 612, 618
        }
    }
}
